---
- name: Clean up contents of a directory
  hosts: all
  become: true
  vars_files:
      - vault.yml
  vars:
    target_dir: /tmp/
  tasks:
    - name: Find all files and directories under the target directory
      find:
        paths: "{{ target_dir }}"
        file_type: any
        recurse: yes
      register: found_items
    - name: Remove all found files and directories
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ found_items.files }}"
